### ISSUE TITLE
Support 'import' directive

### ISSUE THREAD

**Issue by Taluu** [kherge-archive/Wisdom#3]
Hi,

I think something that would be just a kickass feature, used in Symfony config (through a mix between the dependency injection and the config components) would be the ability to import a file. 

The existing key in the imported file would be erased by the ones in the file importing it, and the ones only defined in the imported one would be kept as is.

I would love to propose a PR, but then i guess i'll have to study your code a little bit more...

**Comment by ghost** [comment]
If I understand you correctly, you are asking to support the same exact import functionality of Symfony?

I can do that.

**Comment by Taluu** [comment]
yes, that's right. (:

I'm currently trying to do it though, but if you have the time, i'd be glad to let you do it. (:

**Comment by ghost** [comment]
No worries, I have time.

I will try and knock this out today.

**Comment by ghost** [comment]
Give [this branch](https://github.com/kherge/Wisdom/tree/imports-directive) a try and let me know what you think.

If it works as expected, I'll merge it to master and release it.

**Comment by Taluu** [comment]
Hum, looking at your tests, i think something is wrong. When you're importing a file, it should not erase the value of the file that does the import : it should be the other way around. Example, with files `a.yml`, `b.yml` and `c.yml` :

``` yml
imports:
  - b.yml

a: 42
```

``` yml
imports:
  - c.yml

a: 1337
b: something
```

``` yml
c: yeay
```

So, the expected values should be :

```
array(3) {
  'a' => int(42),
  'b' => string(9) "something"
  'c' => string(4) "yeay"
}
```

But, as i said, by looking at your tests, we should have :

```
array(3) {
  'a' => int(1337),
  'b' => string(9) "something"
  'c' => string(4) "yeay"
}
```

So I think this is kinda wrong, if we look back at how Symfony load this directive...

**Comment by ghost** [comment]
I did some testing, and the results of the imports-directive branch are what Symfony do.

`a.yml` < `b.yml` < `c.yml`

Are you thinking of `%parameters%`?

Sorry, I am confused.

It may be a good idea to make a PR.

**Comment by Taluu** [comment]
Yes, that it what Symfony does, not your changes, if we look at your tests. By reading it, we see that `a_value` takes `941`as a value, instead of expected `012`.

let's take an example in php, to interpret what your code does, and what symfony does.

File `c.php` :

``` php
<?php

$c = 'yeay !';
```

File `b.php` :

``` php
<?php

require 'c.php';

$a = 1337;
$b = 'something';
```

And file `a.php` :

``` php
<?php

require 'b.php';

$a = 42;

var_dump($a, $b, $c);
```

So, if we follow the Symfony behaviour, it should be the following :

```
array(3) {
  'a' => int(42),
  'b' => string(9) "something"
  'c' => string(4) "yeay"
}
```

But, with your behaviour :

```
array(3) {
  'a' => int(1337),
  'b' => string(9) "something"
  'c' => string(4) "yeay"
}
```

I think that the imported file (let's say B) should have its keys _erased_ by the keys in the file (let's say A) that does the import. If a key exists in file A, then it erases the key in file B if it exists. If it does not exist in A but in B, then we don't touch it and have an access to it when loading the conf from A. It is almost the same spirit at what does `array_replace` (should we also consider `array_replace_recursive` in that case ? that's i think another point)

But what you did in here is in the good path, I think. Just this particular point that is not in agreements with what Symfony does...

**Comment by Taluu** [comment]
See what I did in #4, as it does the expected behaviour. It does the same as it does in Symfony (you should check it btw :))

Note, i'm not sure which should be better : either `array_replace` or `array_replace_recursive`... do we want to replace all the keys in one go if it is an array ? Or treat it carefully and replace it step by step ?

**Comment by ghost** [comment]
Aha, you were absolutely correct.

And I think the best way to emulate Symfony's behavior is to use `array_replace`.

If I remember correctly (which I doubt now), Symfony did not recursively replace values.

If this all seems okay right now, I can do the merge to master.

Tests are passing.

**Comment by Taluu** [comment]
Hum, if my memory serves me right, I think Symfony replaces recursively the values, looking back at some of my projects. For example, I defined this `config.yml` file :

``` yaml
doctrine:
    dbal:
        default_connection:   default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
```

And in my `config_dev.yml` :

``` yaml
doctrine:
    dbal:
        connections:
            default:
                dbname:   %database_dev%
```

And my DB is correctly reached on the `dev` env. So I think it is replaced recursively... ?
